# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = xy30249.ap-south-1.aws
user = AKSHITABHATNAGAR
password = Atrium@123
role = HOL_ROLE
warehouse = HOL_WH
database = HOL_DB
schema = HOL_SCHEMA